version: "3.8"

services:

  postgresdb:
    image: postgres
    restart: always

    environment:
      - POSTGRES_DB=prodaja_stanova
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0147
    volumes:
      - db-data:/var/lib/postgresql/data

  prodaja_stanova:
    image: prodaja_stanova:1.1
    depends_on:
      - postgresdb
    ports:
      - "5000:5000"
    volumes:
      - /home/marko/Projekti/prodaja_stanova_docker/uploads:/prodaja_stanova/static/uploads
      - /home/marko/Projekti/prodaja_stanova_docker/template_ugovora:/prodaja_stanova/static/template_ugovora
      - /home/marko/Projekti/prodaja_stanova_docker/ugovori:/prodaja_stanova/static/ugovori

  migration:
    image: prodaja_stanova:1.1
    command: flask db upgrade
    depends_on:
      - postgresdb

volumes:
  db-data:
    driver: local