swagger: "2.0"
info:
  version: "1.0.0"
  title: "Prodaja stanova"
  contact:
    email: "marko.mutavdzic@factoryww.rs"
tags:
- name: "User"
  description: "User routes"
- name: "Apartment"
  description: "Apartment routes"
- name: "Customer"
  description: "Customer routes"
- name: "Apartment Customer"
  description: "Apartment customer routes"
- name: "Report"
  description: "Report routes"
paths:
  /useradd:
    get:
      tags:
      - "User"
      summary: "Dodavanje korisnika"
      description: "Pozdravna test poruka"
      produces:
      - "application/json"
      responses:
        "405":
          description: "Invalid input"
    put:
      tags:
      - "pet"
      summary: "Update an existing pet"
      description: ""
      operationId: "updatePet"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Pet"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
        "405":
          description: "Validation exception"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"