"""empty message

Revision ID: 38faf8612a6f
Revises: 
Create Date: 2021-11-10 09:27:13.527778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38faf8612a6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lamella', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('quadrature', sa.DECIMAL(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('num_rooms', sa.DECIMAL(), nullable=False),
    sa.Column('orientation', sa.Enum('ISTOK', 'ZAPAD', 'SEVER', 'JUG', name='orientation'), nullable=True),
    sa.Column('num_terrace', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(), nullable=False),
    sa.Column('status', sa.Enum('SLOBODAN', 'REZERVISAN', 'PRODAT', name='status'), nullable=True),
    sa.Column('new_construction', sa.Boolean(), nullable=True),
    sa.Column('in_construction', sa.Boolean(), nullable=True),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_entity', sa.Enum('FIZICKO', 'PRAVNO', name='legalentity'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telephone_number', sa.String(length=100), nullable=False),
    sa.Column('pib_jmbg', sa.String(length=50), nullable=False),
    sa.Column('place', sa.String(length=100), nullable=False),
    sa.Column('street', sa.String(length=100), nullable=False),
    sa.Column('num', sa.String(length=100), nullable=False),
    sa.Column('date_of_first_visit', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PRODAVAC', 'FINANSIJE', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apartment_customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_status', sa.Enum('POTENCIJALNI', 'REZERVISAO', 'KUPIO', name='costumerstatus'), nullable=True),
    sa.Column('customer_price', sa.DECIMAL(), nullable=True),
    sa.Column('price_approved', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('currency', sa.Enum('EUR', 'RSD', name='currency'), nullable=True),
    sa.Column('payment_method', sa.Enum('KES', 'KREDIT', 'MESOVITO', name='paymentmethod'), nullable=True),
    sa.Column('deposit_amount', sa.DECIMAL(), nullable=True),
    sa.Column('contract_deadline', sa.Date(), nullable=True),
    sa.Column('bank', sa.String(length=50), nullable=True),
    sa.Column('loan_amount', sa.DECIMAL(), nullable=True),
    sa.Column('cash_amount', sa.DECIMAL(), nullable=True),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartment.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apartment_customer')
    op.drop_table('user')
    op.drop_table('customer')
    op.drop_table('apartment')
    # ### end Alembic commands ###
