"""empty message

Revision ID: c2bd24fa3f58
Revises: 
Create Date: 2021-11-01 15:44:02.645101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2bd24fa3f58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('korisnik',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PRODAVAC', 'FINANSIJE', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kupac',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fizicko_pravno_lice', sa.Enum('FIZICKO', 'PRAVNO', name='fizickopravnolice'), nullable=False),
    sa.Column('naziv_ime', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('broj_telefona', sa.String(length=100), nullable=False),
    sa.Column('pib_jmbg', sa.String(length=50), nullable=False),
    sa.Column('adresa', sa.String(length=100), nullable=False),
    sa.Column('datum_prve_posete', sa.Date(), nullable=True),
    sa.Column('kupac_status', sa.Enum('POTENCIJALNI', 'REZERVISAO', 'KUPIO', name='kupacstatus'), nullable=True),
    sa.Column('cena_za_kupca', sa.DECIMAL(), nullable=False),
    sa.Column('napomena', sa.Text(), nullable=True),
    sa.Column('broj_ugovora', sa.String(length=100), nullable=True),
    sa.Column('datum_ugovora', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lamela', sa.String(length=50), nullable=True),
    sa.Column('kvadratura', sa.DECIMAL(), nullable=False),
    sa.Column('sprat', sa.String(length=50), nullable=False),
    sa.Column('broj_soba', sa.DECIMAL(), nullable=False),
    sa.Column('orjentisanost', sa.Enum('ISTOK', 'ZAPAD', 'SEVER', 'JUG', name='orjentacija'), nullable=True),
    sa.Column('broj_terasa', sa.Integer(), nullable=False),
    sa.Column('cena', sa.DECIMAL(), nullable=False),
    sa.Column('status', sa.Enum('SLOBODAN', 'REZERVISAN', 'PRODAT', name='status'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stan_kupac',
    sa.Column('stan_id', sa.Integer(), nullable=True),
    sa.Column('kupac_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kupac_id'], ['kupac.id'], ),
    sa.ForeignKeyConstraint(['stan_id'], ['stan.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stan_kupac')
    op.drop_table('stan')
    op.drop_table('kupac')
    op.drop_table('korisnik')
    # ### end Alembic commands ###
