"""empty message

Revision ID: 7d0ddfc5b7a4
Revises: 2781f6595543
Create Date: 2021-11-15 14:43:40.006106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d0ddfc5b7a4'
down_revision = '2781f6595543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment', sa.Column('date_created', sa.Date(), nullable=True))
    op.add_column('apartment', sa.Column('date_reserved', sa.Date(), nullable=True))
    op.add_column('apartment', sa.Column('date_sold', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartment', 'date_sold')
    op.drop_column('apartment', 'date_reserved')
    op.drop_column('apartment', 'date_created')
    # ### end Alembic commands ###
