"""empty message

Revision ID: 953f647510b6
Revises: 38faf8612a6f
Create Date: 2021-11-10 14:53:42.985499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953f647510b6'
down_revision = '38faf8612a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    # ### end Alembic commands ###
