"""empty message

Revision ID: 4455775cab47
Revises: 7d0ddfc5b7a4
Create Date: 2021-11-16 16:12:47.218423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4455775cab47'
down_revision = '7d0ddfc5b7a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment_customer', sa.Column('price_approval_by', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartment_customer', 'price_approval_by')
    # ### end Alembic commands ###
